---
title: "Runtime Explorer"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    social: menu
    source_code: embed

runtime: shiny
---

```{r setup, iniclude=FALSE}

library(metricsgraphics)
library(jsonlite)
library(ggplot2)
library(rootSolve)
library(dygraphs)



```

Runtime Histogram
===========================

Inputs {.sidebar}
---------------------------

```{r}

   sliderInput(
                inputId="pre",
                label="Choose the pre-emption rate",
                min = 0,
                max = 0.2,
                value = 0.02,
                step = 0.0001,
                sep="",
                ticks=FALSE
   )

   numericInput(inputId="HiP",label="Price of high 
                          priority VMs",value=5)
   
   numericInput(inputId="LowP",label="Price of low priority VMs",value=1)
                         
```

Row
----------------------------

```{r}

    td1<-read.csv("CalDur.csv")
    td<-subset(td1,CalculationDuration<=40000 & CalculationDuration>0)
    
    pr<-reactive(
        {
          fun<-function(x){
            1-(1-input$pre)^(x/60)-(input$HiP-input$LowP)/input$HiP
          }
        if(fun(40000)<0){
          root=100000
        } else{
          root<-uniroot(fun,c(0,40000))$root
        }
          root
        }
      )
  
    
    renderPlot(
    ggplot(td,aes(x=CalculationDuration))
    +geom_histogram(binwidth=1800,color="gray20",fill="gray75")
    +scale_x_continuous(name="runtime",limits=c(0,40000),breaks=seq(0,40000,5000))
    +geom_vline(aes(xintercept=pr()),color="blue",linetype="dashed",size=1)
    +theme(axis.title=element_text(face="italic"),title=element_text(size=18,face="bold.italic"))
    +ggtitle("Runtime Histogram"))

    renderText({
    paste("The critical runtime is ",round(pr(),digits=2))
  })
  
```

***If the expected runtime is lower than critical runtime, it's profitable to use low priority VMs.***

Cost Ratio Curve
=============================

Inputs2 {.sidebar}
-----------------------------
```{r}

sliderInput(
  inputId="pre2", 
  label="Choose the pre-emption rate", 
  min=0,
  max=1,
  value=0.02,
  step=0.0001,
  sep = "",
  ticks = FALSE
              )

numericInput(inputId="HiP2",label="Price of high 
                          priority VMs",value=5)
   
numericInput(inputId="LowP2",label="Price of low priority VMs",value=1)

```

Row
------------------------

```{r}

renderDygraph({
  x<-1:40000
  fun2<-function(x){
    1-(1-input$pre2)^(x/60)-(input$HiP2-input$LowP2)/input$HiP2
  }
  y<-(1-(1-(1-input$pre2)^(x/60)))*(input$LowP2/input$HiP2)+(1-(1-input$pre2)^(x/60))*((input$LowP2/input$HiP2)+1)
  df2<-data.frame(x,y)
  
  if(fun2(40000)<0){
    root<-100000
  } else{
    root<-uniroot(fun2,c(0,40000))$root
  }
  dygraph(df2,xlab="runtime",ylab="cost ratio",main="Cost Ratio Curve")%>%
    dyAnnotation(round(root),text="A",tooltip="Critical Runtime")%>%
    dyShading(from=0,to=round(root),color="#FAEBD7")%>%
    dyShading(from=round(root),to=40000,color="#F0F8FF")%>%
    dyEvent(round(root),"critical runtime",labelLoc="bottom")%>%
    dyRangeSelector()
  
})



```

***Tip: Double click the graph to reset zooming.***